# Pandas

## 1. 数据结构

### 1.1 Series

Series是一种类似于一维数组的对象，它由一组数据（各种NumPy数据类型）以及一组与之相关的数据标签（即索引）组成。Series的字符串表现形式为：索引在左边，值在右边。

用数组生成Series：

In [1]:
import pandas as pd
import numpy as np

print("用数组生成Series")
obj = pd.Series([4, 7, -5, 3])
print(obj)
print("\r\nSeries的值：")
print(obj.values)
print("\r\nSeries的索引：")
print(obj.index)

用数组生成Series
0    4
1    7
2   -5
3    3
dtype: int64

Series的值：
[ 4  7 -5  3]

Series的索引：
RangeIndex(start=0, stop=4, step=1)


指定Series的index：

In [16]:
print("指定Series的index")
obj2 = pd.Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])
print(obj2)
print("\r\nSeries的值：")
print(obj2.values)
print("\r\nSeries的索引：")
print(obj2.index)

print("\r\n替换index")
obj2.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
print(obj2)

指定Series的index
d    4
b    7
a   -5
c    3
dtype: int64

Series的值：
[ 4  7 -5  3]

Series的索引：
Index(['d', 'b', 'a', 'c'], dtype='object')

替换index
Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64


使用字典生成Series，以及Series相加：

In [61]:
print("使用字典生成Series")
obj3 = pd.Series({'Ohio':45000, 'Texas':71000, 'Oregon':16000, 'Utah':5000})
print(obj3)

print("\r\n使用字典生成Series，并额外指定index，不匹配部分为NaN")
obj4 = pd.Series({'Ohio':45000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}, \
                 index=['California', 'Ohio', 'Oregon', 'Texas'])
print(obj4)

print("\r\nSeries相加，相同索引部分相加")
print(obj3 + obj4)

使用字典生成Series
Ohio      45000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

使用字典生成Series，并额外指定index，不匹配部分为NaN
California        NaN
Ohio          45000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

Series相加，相同索引部分相加
California         NaN
Ohio           90000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64


指定Series及其索引的名字：

In [60]:
print("\r\n指定Series及其索引的名字：")
obj4.name = "population"
obj4.index.name = "state"
print(obj4)


指定Series及其索引的名字：
state
California        NaN
Ohio          45000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64


### 1.2 DataFrame

- DataFrame是一个表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型（数值、字符串、布尔型等）。
- DataFrame既有行索引也有列索引，它可以看做由Series组成的字典（共用同一个索引）。

以下数据都可以用于构建一个DataFrame：

- 二维ndarray：数据矩阵，还可以传入行标和列标
- 由数组、列表或元组组成的字典：每个序列会变成DataFrame的一列，所有序列的长度必须相同
- NumPy的结构化数组：类似于”由数组组成的字典“
- 由Series组成的字典：每个Series会组成一列。如果没有显式指定索引，则各Series的索引会被合并成结果的行索引。
- 由字典组成的字典：各内层字典会成为一列。键会合并成结果的行索引。跟”由Series组成的字典”情况一样。
- 字典或Series的列表：各项将会成为DataFrame的一行。字典键或Series索引的并集将会成为DataFrame的列标。
- 由列表或元组组成的列表：类似于“二维ndarray”
- 另一个DataFrame：该DataFrame的索引将会被沿用，除非显式指定了其他索引。
- NumPy的MaskedArray：类似于“二维ndarray”的情况，只是掩码值在结果DataFrame会变成NaN缺失值。

典型地，可以用字典生成DataFrame：

In [49]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year':[2000, 2001, 2002, 2001, 2002],
        'pop':[1.5, 1.7, 3.6, 2.4, 2.9]}
print("用字典生成DataFrame，key为列的名字，列的顺序默认是乱序的：")
print(pd.DataFrame(data))
print("\r\n可以显式指定列的顺序：")
print(pd.DataFrame(data, columns=['year', 'state', 'pop']))

print("\r\n用字典生成DataFrame，如果显式指定的列中有字典中不存在的列，默认值为NaN。下面这个例子同时指定了索引：")
frame = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five'])
print(frame)

用字典生成DataFrame，key为列的名字，列的顺序默认是乱序的：
   pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

可以显式指定列的顺序：
   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

用字典生成DataFrame，如果显式指定的列中有字典中不存在的列，默认值为NaN。下面这个例子同时指定了索引：
       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN


取一行和取一列的操作：

In [50]:
print("取一列：")
print(frame['state']) # 或者frame.state
print("\r\n取一行：")
print(frame.ix['three']) # loc好像也行

取一列：
one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

取一行：
year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object


修改一列的值：

In [51]:
print("\r\n使用标量修改一整列的每个值：")
frame['debt'] = 16.5
print(frame)
print("\r\n使用ndarray修改一整列的所有值：")
frame.debt = np.arange(5)
print(frame)


使用标量修改一整列的每个值：
       year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

使用ndarray修改一整列的所有值：
       year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4


用Series来修改数据：

In [52]:
print("用Series指定要修改的索引及其对应的值，默认值为NaN")
frame['debt'] = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
print(frame)

用Series指定要修改的索引及其对应的值，默认值为NaN
       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7


新的一列：

In [53]:
frame['eastern'] = (frame.state == 'Ohio')
print(frame)
print("\r\n查看DataFrame有哪些列：")
print(frame.columns)

       year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

查看DataFrame有哪些列：
Index(['year', 'state', 'pop', 'debt', 'eastern'], dtype='object')


DataFrame的转置：

In [56]:
# 字典组成的字典来构建DataFrame
pop = {'Nevada':{2001:2.4, 2002:2.9}, 'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}
frame2 = pd.DataFrame(pop)
print(frame2)
print(frame2.T)

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6
        2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6


切片：

In [57]:
pdata = {'Ohio': frame2['Ohio'][:-1], 'Nevada':frame2['Nevada'][:2]}
print(pd.DataFrame(pdata))

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7


类似于Series，指定索引和列的名称：

In [59]:
frame2.index.name = "year"
frame2.columns.name = "state"
print(frame2)

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6


### 1.3 索引对象

- pandas的索引对象负责管理轴标签和其他元数据(比如轴名称等)。构建Series或DataFrame时，所用到的任何数组或其他序列的标签都会被转换成一个Index。
- Index对象是不可修改的(immutable)，因此用户不能对其进行修改。不可修改性非常重要，因为这样才能使Index对象在多个数据结构之间安全共享。

pandas中的主要index对象：

- `Index` 最泛化的index对象，将轴标签为一个由Python对象组成的NumPy数组
- `Int64Index` 针对整数的特殊index
- `MultiIndex` “层次化”索引对象，表示单个轴上的多层索引
- `DatetimeIndex` 存储纳秒级时间戳
- `PeriodIndex` 针对Period数据的特殊索引

index的方法和属性：

- `append` 连接另一个index对象，产生一个新的Index
- `diff` 计算差集，并得到一个Index
- `intersection` 计算交集
- `union` 计算并集
- `isin` 计算一个指示各值是否包含在参数集合中的布尔型数组
- `delete` 删除索引i处的元素，并得到新的Index
- `drop` 删除传入的值，并得到新的索引
- `insert` 将元素插入到索引i处，并得到新的Index
- `is_monotonic` 当各元素均大于等于前一个元素时，返回True
- `is_unique` 当Index没有重复值时，返回True
- `unique` 计算Index中唯一值的数组

获取Index对象：

In [70]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
idx = obj.index
print(idx)
print(idx[1:])

print("\r\n尝试修改index时会报错：")
try:
    idx[1] = 'd'
except Exception as e:
    print(e)

Index(['a', 'b', 'c'], dtype='object')
Index(['b', 'c'], dtype='object')

尝试修改index时会报错：
Index does not support mutable operations


使用Index对象：

In [72]:
idx = pd.Index(np.arange(3))
obj2 = pd.Series([1.5, -2.5, 0], index=idx)
print(obj2)
print(obj2.index is idx)

0    1.5
1   -2.5
2    0.0
dtype: float64
True


判断列和索引是否存在：

In [76]:
frame = pd.DataFrame({'Nevada':{20001:2.4, 2002:2.9}, 'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}})
print('Ohio' in frame.columns)
print(2003 in frame.index)
print(2001 in frame.index)

True
False
True


## 2. 基本功能

### 2.1 重新索引

- 创建一个适应新索引的新对象，该Series的reindex将会根据新索引进行重排。如果某个索引值当前不存在，就引入缺失值
- 对于时间序列这样的有序数据，重新索引时可能需要做一些插值处理。method选项即可达到此目的。

reindex函数的参数：

- `index` 用作索引的新序列。既可以是Index实例，也可以是其他序列型的Python数据结构。Index会被完全使用，就像没有任何复制一样。
- `method` 插值填充方式。ffill或bfill
- `fill_value` 在重新索引的过程中，需要引入缺失值时使用的替代值
- `limit` 向前或向后填充时的最大填充量
- `level` 在MultiIndex的指定级别上匹配简单索引，否则取其子集
- `copy` 默认为True，无论如何都复制。如果为False，则新旧相等就不复制


In [12]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
print(obj)
print("\r\n重新索引，缺失值使用默认的值：")
print(obj.reindex(['a', 'b', 'c', 'd', 'e']))
print("\r\n重新索引，缺失值使用指定的值：")
print(obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0))

print("\r\n重新索引，指定填充元素的方法")
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
print(obj3)
print(obj3.reindex(range(6), method='ffill'))

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

重新索引，缺失值使用默认的值：
a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

重新索引，缺失值使用指定的值：
a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

重新索引，指定填充元素的方法
0      blue
2    purple
4    yellow
dtype: object
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object


In [18]:
frame = pd.DataFrame(np.arange(9).reshape(3, 3), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])
print(frame)
print("\r\n对DataFrame进行重新索引")
print(frame.reindex(['a', 'b', 'c', 'd']))

print("\r\n重新指定column")
print(frame.reindex(columns=['Texas', 'Utah', 'California']))

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

对DataFrame进行重新索引
   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

重新指定column
   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8


### 2.2 丢弃指定轴上的项

`drop`方法。丢弃某条轴上的一个或多个项很简单，只要有一个索引数组或列表即可。由于需要执行一些数据整理和集合逻辑，所以drop方法返回的是一个在指定轴上删除了指定值的新对象。

In [25]:
obj = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])
print("Series丢弃某些值：")
print(obj.drop(['c', 'd']))

frame = pd.DataFrame(np.arange(16).reshape(4, 4),
                     index=['Ohio', 'Colorado', 'Utah', 'New York'],
                     columns=['one', 'two', 'three', 'four'])
print()
print(frame)
print("\r\nDataFrame按索引drop：")
print(frame.drop(['Colorado', 'Ohio']))
print("\r\nDataFrame按列drop：")
print(frame.drop('two', axis=1))

Series丢弃某些值：
a    0
b    1
e    4
dtype: int64

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

DataFrame按索引drop：
          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

DataFrame按列drop：
          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15


### 2.3 索引以及索引的选取和过滤

- Series索引的工作方式与NumPy相似，但是Series的索引值不只是整数
- 索引是字符串时也可以使用切片，但是与Python中普通的切片不同，其末端是包含的（inclusive）
- 多DataFrame索引就是获取一列或多列，获取行要使用`ix`

In [29]:
obj = pd.Series(np.arange(4), index=['b', 'a', 'c', 'd'])
print("基本索引：")
print(obj['c'])
print("\r\n数字索引依然可以工作：")
print(obj[2])
print(obj[[1, 3]])
print("\r\n字符串索引也可以切片，要注意这个时候是闭区间")
print(obj['b': 'c']) # 注意这里是闭区间
print("\r\n根据条件选择：")
print(obj[obj < 2])

基本索引：
2

数字索引依然可以工作：
2
a    1
d    3
dtype: int64

字符串索引也可以切片，要注意这个时候是闭区间
b    0
a    1
c    2
dtype: int64

根据条件选择：
b    0
a    1
dtype: int64


In [52]:
frame = pd.DataFrame(np.arange(16).reshape(4, 4),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
print(frame)
print("\r\n默认是选择列：")
print(frame['two']) #一列是Series
print("\r\n选择多列：")
print(frame[['three', 'one']]) # 多列是DataFrame

print("\r\n选择行：")
print(frame.ix['Utah']) #一行是Series
print("\r\n通过数字选择行：")
print(frame.ix[[1, 2]]) #多行是DataFrame
print("\r\n同时对行和列进行过滤：")
print(frame.ix[['Utah', 'Ohio'], ['two', 'three']])
print("\r\n切片选择行：")
print(frame[:2])

print("\r\n根据条件选择：")
print(frame[frame.three > 5])

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

默认是选择列：
Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

选择多列：
          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

选择行：
one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

通过数字选择行：
          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

同时对行和列进行过滤：
      two  three
Utah    9     10
Ohio    1      2

切片选择行：
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

根据条件选择：
          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


### 2.4 算数运算和数据对齐

- 自动数据对齐在不重叠的索引处引入了NaN值。

In [4]:
print("加法：")
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
print(s1 + s2)

print("\r\nDataFrame加法，索引和列都必须匹配：")
df1 = pd.DataFrame(np.arange(9).reshape(3, 3), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12).reshape(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(df1 + df2)

加法：
a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

DataFrame加法，索引和列都必须匹配：
            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN


In [8]:
print('数据填充：')
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns = list('abcde'))
print(df1)
print(df2)
print(df1.add(df2, fill_value = 0))
print(df1.reindex(columns = df2.columns, fill_value = 0.0))

数据填充：
     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0
     a    b     c     d    e
0  0.0  1.0   2.0   3.0  0.0
1  4.0  5.0   6.0   7.0  0.0
2  8.0  9.0  10.0  11.0  0.0


In [14]:
print("numpy array减去其中一行：")
arr = np.arange(12).reshape((3, 4))
print(arr)
print(arr[0])
print(arr - arr[0])

print("\r\nDataFrame减去Series（按行）：")
frame = pd.DataFrame(np.arange(12).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
s = frame.ix[0]
print(frame)
print(s)
print(frame - s)

print("\r\nDataFrame减去Series（按列）：")
s = frame['d']
print(frame.sub(s, axis=0))

numpy array减去其中一行：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]

DataFrame减去Series（按行）：
        b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11
b    0
d    1
e    2
Name: Utah, dtype: int64
        b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

DataFrame减去Series（按列）：
        b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1


### 2.5 函数应用

- NumPy的元素级函数都可以用于DataFrame和Series。
- DataFrame的`apply`函数可以用于行或列
- DataFrame的`applymap`函数可用于元素级，Series的`map`函数可用于元素级

In [16]:
print("NumPy的元素级函数用于DataFrame：")
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(frame)
print(np.abs(frame))

NumPy的元素级函数用于DataFrame：
               b         d         e
Utah    1.392685 -1.337089 -1.149561
Ohio    0.032570 -0.388007  0.963771
Texas   0.220362 -0.474904  0.133988
Oregon  0.727001  1.129631  0.175690
               b         d         e
Utah    1.392685  1.337089  1.149561
Ohio    0.032570  0.388007  0.963771
Texas   0.220362  0.474904  0.133988
Oregon  0.727001  1.129631  0.175690


In [21]:
f = lambda x: x.max() - x.min()
print("apply函数作用于列：")
print(frame.apply(f))
print("\r\napply函数作用于行：")
print(frame.apply(f, axis=1))

apply函数作用于列：
b    1.360115
d    2.466720
e    2.113331
dtype: float64

apply函数作用于行：
Utah      2.729774
Ohio      1.351777
Texas     0.695266
Oregon    0.953941
dtype: float64


In [24]:
_format = lambda x: "%.2f" % x
print("applymap可以将函数作用于DataFrame的每个元素：")
print(frame.applymap(_format))
print("\r\nmap可以将函数作用于Series的每个元素：")
print(frame['d'].map(_format))

applymap可以将函数作用于DataFrame的每个元素：
           b      d      e
Utah    1.39  -1.34  -1.15
Ohio    0.03  -0.39   0.96
Texas   0.22  -0.47   0.13
Oregon  0.73   1.13   0.18

map可以将函数作用于Series的每个元素：
Utah      -1.34
Ohio      -0.39
Texas     -0.47
Oregon     1.13
Name: d, dtype: object


### 2.6 排序、排名

- `sort_index`根据索引排序，可以指定轴、升降序、是否原地
- `sort_values`根据值排序
- `rank`得到元素值的排名

In [32]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
print("Series按索引排序：")
print(obj.sort_index())

frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'], columns=list('dabc'))
print("\r\nDataFrame按行索引排序：")
print(frame.sort_index())
print("\r\nDataFrame按列索引排序：")
print(frame.sort_index(axis=1))

Series按索引排序：
a    1
b    2
c    3
d    0
dtype: int64

DataFrame按行索引排序：
       d  a  b  c
one    4  5  6  7
three  0  1  2  3

DataFrame按列索引排序：
       a  b  c  d
three  1  2  3  0
one    5  6  7  4


In [55]:
obj = pd.Series([4, 7, -3, 2])
print("Series根据值排序：")
print(obj.sort_values())

frame = pd.DataFrame({'b':[4, 7, -3, 2], 'a':[0, 1, 0, 1]})
print("\r\nDataFrame根据其中一列的值对行排序：")
print(frame.sort_values(by='b')) # 这里尝试使用axis=1根据行的值对列排序时报错了，暂未解决
print("\r\nDataFrame根据多列的值对行排序：")
print(frame.sort_values(by=['a', 'b']))

Series根据值排序：
2   -3
3    2
0    4
1    7
dtype: int64

DataFrame根据其中一列的值对行排序：
   a  b
2  0 -3
3  1  2
0  0  4
1  1  7

DataFrame根据多列的值对行排序：
   a  b
2  0 -3
0  0  4
3  1  2
1  1  7


In [65]:
obj = pd.Series([9, -5, 9, 4, 2, 0, 4])
# 对应排名（从1开始）：-5(1), 0(2), 2(3), 4(4), 4(5), 9(6), 9(7)
print("对Series使用rank函数，得到每个位置的元素值的rank：")
print(obj.rank()) # 第0个位置的值为9，它的排名是6、7的平均值
print("\r\n可以通过method参数指定rank的方法：")
print(obj.rank(method = 'first'))  # 去第一次出现，不求平均值。

frame = pd.DataFrame({'b':[4.3, 7, -3, 2],
                  'a':[0, 1, 0, 1],
                  'c':[-2, 5, 8, -2.5]})
print("\r\nDataFrame的rank：")
print(frame)
print()
print(frame.rank(axis = 1))

对Series使用rank函数，得到每个位置的元素值的rank：
0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

可以通过method参数指定rank的方法：
0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

DataFrame的rank：
   a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

     a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0
