# numpy.ndarray

## 1 创建（生成）

### 使用普通一维数组生成NumPy一维数

In [1]:
import numpy as np

data = np.array([6, 7.5, 8, 0, 1])
print(data)
print('数组维度：', data.shape)
print('元素类型：', data.dtype)

[ 6.   7.5  8.   0.   1. ]
数组维度： (5,)
元素类型： float64


### 使用普通二维数组生成NumPy二维数组

In [2]:
data = np.array([[1,2,3,4], [5,6,7,8]])
print(data)
print('数组维度：', data.shape)
print('元素类型：', data.dtype)

[[1 2 3 4]
 [5 6 7 8]]
数组维度： (2, 4)
元素类型： int64


### 使用zeros、empty函数

In [3]:
print(np.zeros(10)) # 生成包含10个0的一维数组
print(np.zeros((3, 6))) # 生成3*6的二维数组
print(np.empty((2, 3, 2))) # 生成2*3*2的三维数组，所有元素未初始化

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[[  0.00000000e+000  -1.49166824e-154]
  [  2.96439388e-323   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000]]

 [[  0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   8.34402697e-309]]]


### 使用arange生成连续元素

In [4]:
print(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## 2 元素类型

### 生成数据时指定数据类型

In [5]:
arr = np.array([1, 2, 3], dtype=np.float64)
print(arr.dtype)
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.dtype)

float64
int32


### 使用astype复制数组并转换数据类型

In [6]:
int_arr = np.array([1, 2, 3])
float_arr = int_arr.astype(np.float)
print(int_arr.dtype)
print(float_arr.dtype)

int64
float64


### 使用astype将float转换为int时，小数部分会被舍弃

In [7]:
float_arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
int_arr = float_arr.astype(dtype=np.int)
print(int_arr)

[ 3 -1 -2  0 12 10]


### 使用astype把字符串转换为数值类型，如果失败抛出异常

In [8]:
str_arr = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
float_arr = str_arr.astype(np.float)
print(float_arr)

[  1.25  -9.6   42.  ]


### astype使用其他数组的数据类型作为参考

In [9]:
int_arr = np.arange(10)
float_arr = np.array([.23, 0.270, .357, 0.44, 0.5], dtype=np.float64)
print(int_arr.astype(float_arr.dtype))
print(int_arr) # astype做了复制，数组本身不变

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[0 1 2 3 4 5 6 7 8 9]


## 3 数组和标量之间的运算

### 数组乘法、减法，对应元素相乘、相减

In [10]:
arr = np.array([[1.0, 2.0, 3.0], [4., 5., 6.]])
print(arr * arr)
print(arr - arr)

[[  1.   4.   9.]
 [ 16.  25.  36.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


### 标量作用在数组的每个元素上

In [11]:
print(1 / arr)
print(arr * 0,5)

[[ 1.          0.5         0.33333333]
 [ 0.25        0.2         0.16666667]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]] 5


## 4 索引和切片

### 通过索引访问二维数组某一行或某个元素

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[2])
print(arr[0][2])
print(arr[0, 2]) #普通Python数组不能用

[7 8 9]
3
3


### 对更高维数组的访问和操作

In [13]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print('arr[0]: ', arr[0]) # 结果是二维数组
print('arr[1, 0]: ', arr[1, 0]) # 结果是一维数组
old_values = arr[0].copy() # 复制，否则是引用
arr[0] = 42 # 把arr[0]的所有元素设置为同一个值
print('arr new: ', arr)
arr[0] = old_values
print('arr old: ', arr)

arr[0]:  [[1 2 3]
 [4 5 6]]
arr[1, 0]:  [7 8 9]
arr new:  [[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
arr old:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### 使用切片操作和访问数组

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[1: 6]) # arr[1]到arr[5]
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[:2]) # 第1、2行
print(arr[:2, 1:]) #第1、2行，第2、3列
print(arr[:, :1]) #第1列
arr[:2, 1:] = 0 # 第1、2行，第2、3列的元素设置为0
print(arr)

[2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[1]
 [4]
 [7]]
[[1 0 0]
 [4 0 0]
 [7 8 9]]


## 5 布尔型索引

In [15]:
import numpy.random as np_random

name_arr = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
rnd_arr = np_random.random((7, 4)) # 随机7*4数组

print(rnd_arr)
print(name_arr == 'Bob') # 返回布尔数组

[[ 0.37455519  0.49705696  0.44484209  0.50077587]
 [ 0.57502363  0.65902964  0.36473502  0.08568679]
 [ 0.62295093  0.10683726  0.93098799  0.13004762]
 [ 0.31639005  0.05100917  0.72946184  0.70777647]
 [ 0.40331729  0.63656192  0.80919718  0.62781145]
 [ 0.00401119  0.61462827  0.49965417  0.74348256]
 [ 0.28854451  0.90000489  0.02247753  0.96208622]]
[ True False False  True False False False]


### 利用布尔数组选择行

In [16]:
print(rnd_arr[name_arr == 'Bob'])

[[ 0.37455519  0.49705696  0.44484209  0.50077587]
 [ 0.31639005  0.05100917  0.72946184  0.70777647]]


### 加上切片限制列的范围

In [17]:
print(rnd_arr[name_arr == 'Bob', :2])

[[ 0.37455519  0.49705696]
 [ 0.31639005  0.05100917]]


### 对布尔数组的内容取反

In [18]:
print(rnd_arr[~(name_arr == 'Bob')])

[[ 0.57502363  0.65902964  0.36473502  0.08568679]
 [ 0.62295093  0.10683726  0.93098799  0.13004762]
 [ 0.40331729  0.63656192  0.80919718  0.62781145]
 [ 0.00401119  0.61462827  0.49965417  0.74348256]
 [ 0.28854451  0.90000489  0.02247753  0.96208622]]


### 逻辑运算混合结果

In [19]:
mask_arr = (name_arr == 'Bob') | (name_arr == 'Will')
print(rnd_arr[mask_arr])

[[ 0.37455519  0.49705696  0.44484209  0.50077587]
 [ 0.62295093  0.10683726  0.93098799  0.13004762]
 [ 0.31639005  0.05100917  0.72946184  0.70777647]
 [ 0.40331729  0.63656192  0.80919718  0.62781145]]


### 设置选择的元素

In [20]:
rnd_arr[name_arr != 'Joe'] = 7
print(rnd_arr)

[[  7.00000000e+00   7.00000000e+00   7.00000000e+00   7.00000000e+00]
 [  5.75023634e-01   6.59029642e-01   3.64735022e-01   8.56867873e-02]
 [  7.00000000e+00   7.00000000e+00   7.00000000e+00   7.00000000e+00]
 [  7.00000000e+00   7.00000000e+00   7.00000000e+00   7.00000000e+00]
 [  7.00000000e+00   7.00000000e+00   7.00000000e+00   7.00000000e+00]
 [  4.01119104e-03   6.14628273e-01   4.99654169e-01   7.43482557e-01]
 [  2.88544510e-01   9.00004888e-01   2.24775258e-02   9.62086218e-01]]


## 6 花式索引

In [21]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
print(arr)

[[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]
 [ 7.  7.  7.  7.]]


In [23]:
# 打印arr[4]、arr[3]、arr[0]、arr[6]
print(arr[[4, 3, 0, 6]])

[[ 4.  4.  4.  4.]
 [ 3.  3.  3.  3.]
 [ 0.  0.  0.  0.]
 [ 6.  6.  6.  6.]]


In [24]:
# 打印arr[-3]、arr[-5]、arr[-7]
print(arr[[-3, -5, -7]])

[[ 5.  5.  5.  5.]
 [ 3.  3.  3.  3.]
 [ 1.  1.  1.  1.]]


In [25]:
arr = np.arange(32).reshape((8, 4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [26]:
# 打印arr[1,0]、arr[5,3]、arr[7,1]、arr[2,2]
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])

[ 4 23 29 10]


In [27]:
# 1572行的0312列
print(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [28]:
# 跟上面一样，可读性更好
print(arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


## 7 数组装置和轴对换

In [29]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### 装置矩阵做点积

In [30]:
arr = np_random.randn(6, 3)
print(arr)
print(np.dot(arr.T, arr))

[[ 0.38682824 -1.03698932  0.95931903]
 [ 1.03237178 -1.75441083  0.90010547]
 [ 0.21610937  1.27400966 -1.95489516]
 [ 0.18153369 -0.86519831  0.11092879]
 [ 0.43619805 -1.34088836 -0.34133304]
 [-0.78804298 -1.71010956  0.90379578]]
[[  2.1063658   -1.33133127   0.03688261]
 [ -1.33133127  11.24742924  -6.24838942]
 [  0.03688261  -6.24838942   6.49775823]]


### 高维矩阵转换

In [31]:
arr = np.arange(16).reshape((2, 2, 4))
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [32]:
'''
详细解释：
arr数组的内容为
- a[0][0] = [0, 1, 2, 3]
- a[0][1] = [4, 5, 6, 7]
- a[1][0] = [8, 9, 10, 11]
- a[1][1] = [12, 13, 14, 15]
transpose的参数为坐标，正常顺序为(0, 1, 2, ... , n - 1)，
现在传入的为(1, 0, 2)代表a[x][y][z] = a[y][x][z]，第0个和第1个坐标互换。
- a'[0][0] = a[0][0] = [0, 1, 2, 3]
- a'[0][1] = a[1][0] = [8, 9, 10, 11]
- a'[1][0] = a[0][1] = [4, 5, 6, 7]
- a'[1][1] = a[1][1] = [12, 13, 14, 15]
'''
print(arr.transpose(1, 0, 2))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [33]:
# 直接交换第1和第2个坐标
print(arr.swapaxes(1, 2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]
