# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation.

The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

以np的名字导入numpy包

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)
输出numpy的版本和配置

In [25]:
print(np.__version__)
print('============================================================')
np.show_config()

1.11.3
blas_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread

#### 3. Create a null vector of size 10 (★☆☆)

In [20]:
Z = np.zeros(10)
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


#### 4. How to find the memory size of any array (★☆☆)

In [8]:
Z = np.zeros((10, 10))
print('%d bytes' % (Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

在命令行下运行 `C://ProgramData//Anaconda3//python.exe -c "import numpy; numpy.info(numpy.add)"`

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
Z = np.arange(10)
Z = Z[::-1]
print(Z)

[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [18]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
Z = np.random.random((3, 3, 3))
print(Z)

[[[ 0.69369363  0.58537531  0.44051558]
  [ 0.30540343  0.94701859  0.43557062]
  [ 0.34582901  0.60055029  0.46504658]]

 [[ 0.39410753  0.15822226  0.91639667]
  [ 0.2189191   0.55509188  0.13152221]
  [ 0.39255426  0.45030566  0.56232476]]

 [[ 0.49247224  0.37558132  0.14216241]
  [ 0.09898743  0.12087414  0.85601123]
  [ 0.26627518  0.37960737  0.42081188]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [29]:
Z = np.random.random((10, 10))
print(Z.min(), Z.max())

0.00463274937261 0.991821685714


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [27]:
Z = np.random.random(30)
print(Z.mean())

0.49634479228


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [30]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [38]:
Z = np.arange(16).reshape(4, 4)
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[ 0  0  0  0  0  0]
 [ 0  0  1  2  3  0]
 [ 0  4  5  6  7  0]
 [ 0  8  9 10 11  0]
 [ 0 12 13 14 15  0]
 [ 0  0  0  0  0  0]]


#### 17. What is the result of the following expression? (★☆☆)

In [41]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [49]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [14]:
Z = np.zeros((8, 8), dtype=np.int)
Z[::2,1::2] = 1
Z[1::2, ::2] =1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [11]:
idx = np.unravel_index(100, (6, 7, 8))
print(idx)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [17]:
Z = np.array([[0, 1], [1, 0]], dtype=np.int)
Z = np.tile(Z, (4, 4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [19]:
Z = np.random.random((5, 5))
Z = (Z - Z.min()) / (Z.max() - Z.min())
print(Z)

[[ 0.67537689  0.13743758  0.53433988  0.77775111  0.35650676]
 [ 0.59477946  0.          0.81493687  0.44224706  0.79468269]
 [ 0.64530049  0.12275393  0.21434346  0.12284977  0.82291526]
 [ 0.89728165  1.          0.4188241   0.91794734  0.33268645]
 [ 0.15230309  0.05208088  0.27788789  0.38465784  0.51824574]]


#### 23. Create a custom dtype that describes a color as four unisgned bytes (RGBA) (★☆☆)

In [28]:
color = np.dtype([
    ('r', np.ubyte, 1),
    ('g', np.ubyte, 1),
    ('b', np.ubyte, 1),
    ('a', np.ubyte, 1)
])
np.dtype(color)

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [32]:
Z = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [35]:
Z = np.arange(15)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆)

In [8]:
# Author: Jake VanderPlas

print(sum(range(5),-1))

print(np.sum(range(5), -1)) # -1: axis=-1   If axis is negative it counts from the last to the first axis.

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z # ?
1j*Z
Z/1/1
Z<Z>Z # ?

#### 28. What are the result of the following expressions?

In [37]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[ -2.14748365e+09]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  from ipykernel import kernelapp as app


#### 29. How to round away from zero a float array ? (★☆☆)

In [42]:
Z = np.random.uniform(-10,+10,10)
print(Z)
Z = np.copysign(np.ceil(np.abs(Z)), Z) # 不直接使用ceil，例如-4.3直接使用是-4，这里的结果是-5
print(Z)

[ 2.88960466 -4.02814668  3.49203917 -7.48785921 -0.02779605  4.82877833
 -2.18914762  6.29530529 -1.62304738 -4.4424875 ]
[ 3. -5.  4. -8. -1.  5. -3.  7. -2. -5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [2]:
Z1 = np.arange(15)
Z2 = np.arange(10, 25)
print(np.intersect1d(Z1, Z2))

[10 11 12 13 14]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [13]:
defaults = np.seterr(all='ignore')
Z = np.ones(1) / 0

_ = np.seterr(**defaults)
Z = np.ones(1) / 0

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:5: RuntimeWarning: divide by zero encountered in true_divide


#### 32. Is the following expressions true? (★☆☆)

In [14]:
np.sqrt(-1) == np.emath.sqrt(-1)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [20]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday, today, tomorrow)

2017-05-03 2017-05-04 2017-05-05
