# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation.

The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

以np的名字导入numpy包

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)
输出numpy的版本和配置

In [25]:
print(np.__version__)
print('============================================================')
np.show_config()

1.11.3
blas_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread

#### 3. Create a null vector of size 10 (★☆☆)

In [20]:
Z = np.zeros(10)
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


#### 4. How to find the memory size of any array (★☆☆)

In [8]:
Z = np.zeros((10, 10))
print('%d bytes' % (Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

在命令行下运行 `C://ProgramData//Anaconda3//python.exe -c "import numpy; numpy.info(numpy.add)"`

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
Z = np.arange(10)
Z = Z[::-1]
print(Z)

[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [18]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
Z = np.random.random((3, 3, 3))
print(Z)

[[[ 0.69369363  0.58537531  0.44051558]
  [ 0.30540343  0.94701859  0.43557062]
  [ 0.34582901  0.60055029  0.46504658]]

 [[ 0.39410753  0.15822226  0.91639667]
  [ 0.2189191   0.55509188  0.13152221]
  [ 0.39255426  0.45030566  0.56232476]]

 [[ 0.49247224  0.37558132  0.14216241]
  [ 0.09898743  0.12087414  0.85601123]
  [ 0.26627518  0.37960737  0.42081188]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [29]:
Z = np.random.random((10, 10))
print(Z.min(), Z.max())

0.00463274937261 0.991821685714


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [27]:
Z = np.random.random(30)
print(Z.mean())

0.49634479228


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [30]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [38]:
Z = np.arange(16).reshape(4, 4)
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[ 0  0  0  0  0  0]
 [ 0  0  1  2  3  0]
 [ 0  4  5  6  7  0]
 [ 0  8  9 10 11  0]
 [ 0 12 13 14 15  0]
 [ 0  0  0  0  0  0]]


#### 17. What is the result of the following expression? (★☆☆)

In [41]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [49]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [14]:
Z = np.zeros((8, 8), dtype=np.int)
Z[::2,1::2] = 1
Z[1::2, ::2] =1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [11]:
idx = np.unravel_index(100, (6, 7, 8))
print(idx)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [17]:
Z = np.array([[0, 1], [1, 0]], dtype=np.int)
Z = np.tile(Z, (4, 4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [19]:
Z = np.random.random((5, 5))
Z = (Z - Z.min()) / (Z.max() - Z.min())
print(Z)

[[ 0.67537689  0.13743758  0.53433988  0.77775111  0.35650676]
 [ 0.59477946  0.          0.81493687  0.44224706  0.79468269]
 [ 0.64530049  0.12275393  0.21434346  0.12284977  0.82291526]
 [ 0.89728165  1.          0.4188241   0.91794734  0.33268645]
 [ 0.15230309  0.05208088  0.27788789  0.38465784  0.51824574]]


#### 23. Create a custom dtype that describes a color as four unisgned bytes (RGBA) (★☆☆)

In [28]:
color = np.dtype([
    ('r', np.ubyte, 1),
    ('g', np.ubyte, 1),
    ('b', np.ubyte, 1),
    ('a', np.ubyte, 1)
])
np.dtype(color)

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [32]:
Z = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [35]:
Z = np.arange(15)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆)

In [8]:
# Author: Jake VanderPlas

print(sum(range(5),-1))

print(np.sum(range(5), -1)) # -1: axis=-1   If axis is negative it counts from the last to the first axis.

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z # ?
1j*Z
Z/1/1
Z<Z>Z # ?

#### 28. What are the result of the following expressions?

In [37]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[ -2.14748365e+09]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  from ipykernel import kernelapp as app


#### 29. How to round away from zero a float array ? (★☆☆)

In [42]:
Z = np.random.uniform(-10,+10,10)
print(Z)
Z = np.copysign(np.ceil(np.abs(Z)), Z) # 不直接使用ceil，例如-4.3直接使用是-4，这里的结果是-5
print(Z)

[ 2.88960466 -4.02814668  3.49203917 -7.48785921 -0.02779605  4.82877833
 -2.18914762  6.29530529 -1.62304738 -4.4424875 ]
[ 3. -5.  4. -8. -1.  5. -3.  7. -2. -5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [2]:
Z1 = np.arange(15)
Z2 = np.arange(10, 25)
print(np.intersect1d(Z1, Z2))

[10 11 12 13 14]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [13]:
defaults = np.seterr(all='ignore')
Z = np.ones(1) / 0

_ = np.seterr(**defaults)
Z = np.ones(1) / 0

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:5: RuntimeWarning: divide by zero encountered in true_divide


#### 32. Is the following expressions true? (★☆☆)

In [14]:
np.sqrt(-1) == np.emath.sqrt(-1)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [20]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday, today, tomorrow)

2017-05-03 2017-05-04 2017-05-05


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [7]:
Z = np.arange('2017-07', '2017-08', dtype='datetime64[D]')
print(Z)

['2017-07-01' '2017-07-02' '2017-07-03' '2017-07-04' '2017-07-05'
 '2017-07-06' '2017-07-07' '2017-07-08' '2017-07-09' '2017-07-10'
 '2017-07-11' '2017-07-12' '2017-07-13' '2017-07-14' '2017-07-15'
 '2017-07-16' '2017-07-17' '2017-07-18' '2017-07-19' '2017-07-20'
 '2017-07-21' '2017-07-22' '2017-07-23' '2017-07-24' '2017-07-25'
 '2017-07-26' '2017-07-27' '2017-07-28' '2017-07-29' '2017-07-30'
 '2017-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [14]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A, B, out=B)
np.negative(A, out=A)
np.multiply(B, A / 2, out=B)
print(B)

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [28]:
Z = np.random.uniform(0, 10, 10)
print(Z)
print(np.floor(Z))
print(np.ceil(Z) - 1)
print(Z - Z % 1)
print(np.trunc(Z))
print(Z.astype(int))

[ 8.25146747  6.91221999  2.77809209  2.59204387  5.07023761  8.24995959
  3.87700393  8.04045808  7.48921172  5.82764753]
[ 8.  6.  2.  2.  5.  8.  3.  8.  7.  5.]
[ 8.  6.  2.  2.  5.  8.  3.  8.  7.  5.]
[ 8.  6.  2.  2.  5.  8.  3.  8.  7.  5.]
[ 8.  6.  2.  2.  5.  8.  3.  8.  7.  5.]
[8 6 2 2 5 8 3 8 7 5]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [36]:
Z = np.arange(5)
print(np.tile(Z, (5, 1)))

#另一种方法
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [47]:
def ggg():
    for a in range(10):
        yield a
    
Z = np.fromiter(ggg(), dtype=np.float, count=-1)
print(Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [53]:
np.linspace(0, 1, 12)[1:-1]

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [57]:
Z = np.random.random(10)
print(Z)
Z.sort()
print(Z)

[ 0.54984509  0.5756908   0.66962356  0.10100397  0.74115721  0.70647852
  0.91817805  0.45867005  0.62291896  0.18883703]
[ 0.10100397  0.18883703  0.45867005  0.54984509  0.5756908   0.62291896
  0.66962356  0.70647852  0.74115721  0.91817805]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [72]:
import timeit

Z = np.array([1] * 300)
print(np.add.reduce(Z))
print(np.sum(Z))

# 时间消耗
print(timeit.timeit('np.sum(data)', 'import numpy as np; data = np.array([1] * 300)', number=100000))
print(timeit.timeit('np.add.reduce(data)', 'import numpy as np; data = np.array([1] * 300)', number=100000))

300
300
0.5149214288603616
0.24748610196184018


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [122]:
A = np.random.randint(0, 2, 3)
B = np.random.randint(0, 2, 3)
print(A, B)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
print(np.allclose(A, B))

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
print(np.array_equal(A, B))

[1 1 0] [0 1 0]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [124]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [134]:
Z = np.random.random((10, 2))
print(Z)
R = np.sqrt(Z[:, 0]**2 + Z[:, 1]**2)
T = np.arctan(Z[:, 1] / Z[:, 0])
print(R, T)             

[[ 0.94373338  0.36027621]
 [ 0.32440025  0.80921515]
 [ 0.75372879  0.72255957]
 [ 0.5592454   0.65750787]
 [ 0.51102428  0.09974685]
 [ 0.98576359  0.6164251 ]
 [ 0.34055511  0.55822373]
 [ 0.56272703  0.76830647]
 [ 0.51235357  0.80251043]
 [ 0.77077161  0.85742684]]
[ 1.01016417  0.87181688  1.04412616  0.86317554  0.52066808  1.16263053
  0.65390482  0.95234265  0.95211826  1.15293958] [ 0.36468085  1.18952934  0.76428807  0.86598121  0.19276635  0.5588348
  1.02300587  0.93863829  1.00259167  0.83856954]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)  

In [145]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[ 0.17635333  0.80060867  0.78518588  0.81637549  0.02322785  0.79275125
  0.24249429  0.70849693  0.02347673  0.55977558]
[ 0.17635333  0.80060867  0.78518588  0.          0.02322785  0.79275125
  0.24249429  0.70849693  0.02347673  0.55977558]


#### 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

In [154]:
Z = np.zeros((5, 5), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(Z)

[[(0.0, 0.0) (0.25, 0.0) (0.5, 0.0) (0.75, 0.0) (1.0, 0.0)]
 [(0.0, 0.25) (0.25, 0.25) (0.5, 0.25) (0.75, 0.25) (1.0, 0.25)]
 [(0.0, 0.5) (0.25, 0.5) (0.5, 0.5) (0.75, 0.5) (1.0, 0.5)]
 [(0.0, 0.75) (0.25, 0.75) (0.5, 0.75) (0.75, 0.75) (1.0, 0.75)]
 [(0.0, 1.0) (0.25, 1.0) (0.5, 1.0) (0.75, 1.0) (1.0, 1.0)]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [170]:
X = np.arange(8)
Y = X + 0.5
Z = 1.0 / np.subtract.outer(X, Y)

print(Z)
print(np.linalg.det(Z))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.16363712


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [176]:
print(np.iinfo(np.int16).min, np.iinfo(np.int16).max)

print(np.finfo(np.float32).min, np.finfo(np.float32).max, np.finfo(np.float32).eps)

-32768 32767
-3.40282e+38 3.40282e+38 1.19209e-07


#### 49. How to print all the values of an array? (★★☆)

In [179]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16, 16))
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 

#### 50. How to find the closest value (to a given scalar) in an array? (★★☆)

In [186]:
Z = np.random.random(5)
x = np.abs(Z - 0.5).argmin()
print(Z)
print(x, Z[x])

[ 0.07972931  0.28087575  0.70584424  0.47057343  0.84943698]
3 0.470573431918


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [190]:
Z = np.zeros(5, dtype=[
    ('position', [('x', float, 1), ('y', float, 1)]),
    ('color', [('r', float), ('g', float), ('b', float)])
])
print(Z)

[((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0))]
