# NumPy

首先介绍`numpy.info`函数，它用于获取NumPy内函数的帮助：

In [8]:
import numpy as np

np.info(np.array)

array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an
    object whose __array__ method returns an array, or any
    (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then
    the type will be determined as the minimum type required
    to hold the objects in the sequence.  This argument can only
    be used to 'upcast' the array.  For downcasting, use the
    .astype(t) method.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy
    will only be made if __array__ returns a copy, if obj is a
    nested sequence, or if a copy is needed to satisfy any of the other
    requirements (`dtype`, `order`, etc.).
order : {'C', 'F', 'A'}, optional
    Specify the order of the array.  If order is 'C', then the array
    will be in C-contiguous order (last-index varies the 

## 1. NumPy的ndarray

### 1.1 创建ndarray

- `array` 将输入数据（列表、元组、数组或其它序列类型）转换为ndarray。要么推断出dtype，要么显示指定dtype。默认直接复制输入数据。
- `asarray` 将输入转换为ndarray，如果输入本身就是一个ndarray就不进行复制。
- `arange` 类似于Python内置的`range`，但返回一个ndarray而不是列表。
- `ones`, `ones_like` 根据指定形状和dtype创建一个全1的数组。ones_like以另一个数组为参数，并根据其形状和dtype创建一个全1数组。
- `zeros`, `zeros_like` 类似于`ones`和`ones_like`，只不过产生的是全0数组而已。
- `empty`, `empty_like` 创建数组，只分配内存空间但不填充任何值
- `eye`, `identity` 创建对角矩阵、单位矩阵。单位矩阵一定是方阵，但对角矩阵不一定

In [18]:
Z = np.array([2, 4, 1, 6, 10])
print(Z)
Z = np.array([2, 4, 1, 6, 10], dtype=float)
print(Z)

Z = np.eye(3)
print(Z)

[ 2  4  1  6 10]
[  2.   4.   1.   6.  10.]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### 1.2 数据类型

- `int8`, `uint8` 有/无符号的8位整型
- `int16`, `uint16` 有/无符号的16位整型
- `int32`, `uint32` 有/无符号的32位整型
- `int64`, `uint64` 有/无符号的64位整型
- `float16` 半精度浮点数
- `float32` 标准的单精度浮点数，与C的float兼容
- `float64` 标准的双精度浮点数，与C的double和Python的float兼容
- `float128` 扩展精度浮点数
- `complex`, `comples64`, `complex128` 分别用128位、64位、128位表示的复数
- `bool` 存储True和Flase值的布尔类型
- `object` Python对象类型
- `string_` 字符串
- `unicode_` unicode类型

除了创建ndarray时使用`dtype`参数指定数据类型外，可以使用`astype`函数显示的转换类型。

`itemsize`函数可以查看数据类型的size。

In [37]:
Z = np.array([2, 4, 1, 6, 10], dtype=np.complex)
print(Z.itemsize)
Z = Z.astype(np.complex64)
print(Z.itemsize)

16
8


### 1.3 ndarray与标量的运算

- 数组与标量（包括长度为1的数组）的算术运算：将标量值运用到数组的每个元素
- 数组与数组：大小相等才能运算，也是运用到数组的每个元素

In [41]:
X = np.array([1, 2, 3])
Y = np.array([3, 2, 5])
print(1 / X)
print(X * Y)

[ 1.          0.5         0.33333333]
[ 3  4 15]


### 1.4 索引与切片

索引和切片跟Python默认的索引和切片出入不大，其强大之处需要慢慢体会，下面两个例子自己感受下：

In [45]:
# 创建一个2维数组，使所有边界上的元素都为1，内部的元素都为0
Z = np.ones((6, 6))
Z[1:-1, 1:-1] = 0
print(Z)

# 创建一个跳棋盘布局的数组
Z = np.zeros((6, 6))
Z[::2,1::2] = 1
Z[1::2, ::2] =1
print(Z)

[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.]]
[[ 0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.]]


### 1.5 布尔型索引

- 布尔型数组的长度必须跟被索引的轴长度一致。
- 可以将布尔型数组跟切片、整数（或整数序列）混合使用

In [54]:
name_arr = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
rnd_arr = np.random.randn(7, 4)

print(rnd_arr)
print(name_arr == 'Bob') # 返回布尔数组，元素等于'Bob'为True，否则False。
print(rnd_arr[name_arr == 'Bob']) # 利用布尔数组选择行
print(rnd_arr[name_arr == 'Bob', :2]) # 增加限制打印列的范围

[[ 0.0467935  -2.23240704 -0.84316688 -0.93206582]
 [ 0.335597   -0.91785137 -0.84906898 -0.34904434]
 [ 0.88452287 -0.57010837  1.30963692 -0.79191444]
 [ 0.38402722 -0.58489885  0.69678608  0.23887355]
 [-0.65352635 -0.57346281  1.61155421  0.62501593]
 [ 0.16888557  0.3387558   0.05291106  1.07061632]
 [-1.4870258   0.30384522  1.14928683  1.57219728]]
[ True False False  True False False False]
[[ 0.0467935  -2.23240704 -0.84316688 -0.93206582]
 [ 0.38402722 -0.58489885  0.69678608  0.23887355]]
[[ 0.0467935  -2.23240704]
 [ 0.38402722 -0.58489885]]


### 1.6 花式索引

- 花式索引（Fancy indexing）是一个NumPy术语，它指的是利用整数数组进行索引。

In [67]:
arr = np.tile(np.arange(8).reshape(8, -1), (1, 4)).astype(float)
print(arr)

print(arr[[4, 3, 0, 6]]) # 打印arr[4]、arr[3]、arr[0]和arr[6]。
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]]) # 打印arr[1, 0]、arr[5, 3]，arr[7, 1]和arr[2, 2]
print(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]) # 1572行的0312列
print(arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]) # 可读性更好的写法

[[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]
 [ 7.  7.  7.  7.]]
[[ 4.  4.  4.  4.]
 [ 3.  3.  3.  3.]
 [ 0.  0.  0.  0.]
 [ 6.  6.  6.  6.]]
[ 1.  5.  7.  2.]
[[ 1.  1.  1.  1.]
 [ 5.  5.  5.  5.]
 [ 7.  7.  7.  7.]
 [ 2.  2.  2.  2.]]
[[ 1.  1.  1.  1.]
 [ 5.  5.  5.  5.]
 [ 7.  7.  7.  7.]
 [ 2.  2.  2.  2.]]


### 1.7 数组转置和轴对换

- 转置：`arr.T`比较简单，就是常规的转置，`arr.transpose`可以增加坐标作为参数
- 点积：`numpy.dot`
- 轴交换：`swapaxes`

In [86]:
Z = np.arange(9).reshape((3, 3))
print(Z.T)
print(Z.transpose())


print('')

'''
详细解释：
arr数组的内容为
- a[0][0] = [0, 1, 2, 3]
- a[0][1] = [4, 5, 6, 7]
- a[1][0] = [8, 9, 10, 11]
- a[1][1] = [12, 13, 14, 15]
transpose的参数为坐标，正常顺序为(0, 1, 2, ... , n - 1)，
现在传入的为(1, 0, 2)代表a[x][y][z] = a[y][x][z]，第0个和第1个坐标互换。
- a'[0][0] = a[0][0] = [0, 1, 2, 3]
- a'[0][1] = a[1][0] = [8, 9, 10, 11]
- a'[1][0] = a[0][1] = [4, 5, 6, 7]
- a'[1][1] = a[1][1] = [12, 13, 14, 15]
'''
Z = np.arange(16).reshape((2, 2, 4))
print(Z)
print(Z.transpose((1, 0, 2)))


print('')
print(Z.swapaxes(1, 2))

print(Z[1,1,3])

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]
15


### 1.8 快速的元素级函数

一元函数：

- `abs`, `fabs` 计算整数、浮点数或复数的绝对值。对于非复数值，可以使用更快的fabs。
- `sqrt` 计算各元素的平方根。相当于arr\*\*0.5
- `sqare` 计算各元素的平方。相当于arr\*\*2
- `exp` 计算各元素的e^x
- `log`, `log10`, `log2`, `log1p` 分别为自然对数、底数为10的log、底数为2的log和log(1+x)
- `sign` 计算各元素的正负号：1（正数）、0（零）、-1（负数）
- `ceil` 计算各元素的ceiling值，即大于等于该值的最小整数
- `floor` 计算各元素的floor值，即小于等于该值的最小整数
- `rint` 将各元素值四舍五入到最接近的整数，保留dtype
- `modf` 将数组的小数部分与整数部分以两个独立数组的形式返还
- `isnan` 返回一个表示“哪些值时NaN”的布尔型数组
- `isfinite`, `isinf` 分别返回一个表示“哪些元素是有限的（非inf，非NaN）”或“哪些元素是无穷的”的布尔型数组
- `cos`, `cosh`, `sin`, `sinh`, `tan`, `tanh` 普通型或双曲型三角函数
- `arccos`, `arccosh`, `arcsin`, `arcsinh`, `arctan`, `arctanh` 反三角函数
- `logical_not` 计算各元素not x的真值，相当于~arr

二元函数：

- `add` 将数组中对应元素相加
- `subtract` 从第一个数组中减去第二个数组中的元素
- `multiply` 数组元素相乘
- `divide`, `floor_divide` 除法或向下取整除法
- `power` 对第一个数组中的元素A和第二个数组中对应位置的元素B，计算A^B
- `maximum`, `fmax` 元素级的最大值计算。`fmax`将忽略NaN
- `minimum`, `fmin` 元素级的最小值计算。`fmin`将忽略NaN
- `mod` 元素级的求模计算
- `copysign` 将第二个数组中的符号复制给第一个数组中的值
- `greater`, `greater_equal`, `less`, `less_equal`, `equal`, `not_equal` 执行元素级的比较，最终产生布尔型数组
- `logical_and`, `logical_or`, `logical_xor` 执行元素级的真值逻辑运算，最终产生布尔型数组


## 2. 数据处理

- NumPy数组使你可以将许多种数据处理任务表述为简洁的数组表达式（否则需要编写循环）。用数组表达式代替循环的做法，通常被称为矢量化。
- 矢量化数组运算要比等价的纯Python方式快上一两个数量级

### 2.1 将条件逻辑表述为数组运算

- `numpy.where` 根据条件来分别从两个数组中选择值。对比下面例子中的“列表推导”方法（速度不够快、无法应用于高维数组）

In [89]:
'''
关于zip函数的一点解释，zip可以接受任意多参数，然后重新组合成1个tuple列表。
zip([1, 2, 3], [4, 5, 6], [7, 8, 9])
返回结果：[(1, 4, 7), (2, 5, 8), (3, 6, 9)]
'''
print()'通过真值表选择元素'
x_arr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y_arr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = [(x if c else y) for x, y, c in zip(x_arr, y_arr, cond)] # 通过列表推导实现
print(result)
print(np.where(cond, x_arr, y_arr))  # 使用NumPy的where函数

print 'where嵌套'
cond_1 = np.array([True, False, True, True, False])
cond_2 = np.array([False, True, False, True, False])
# 传统代码如下
result = []
for i in xrange(len(cond)):
    if cond_1[i] and cond_2[i]:
        result.append(0)
    elif cond_1[i]:
        result.append(1)
    elif cond_2[i]:
        result.append(2)
    else:
        result.append(3)
print result
# np版本代码
result = np.where(cond_1 & cond_2, 0, \
          np.where(cond_1, 1, np.where(cond_2, 2, 3)))
print result

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]
[ 1.1  2.2  1.3  1.4  2.5]
